### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alexander-somov** [Dobroserdoff/parsek#4]
I have made TODO in the TODO.md. Please check it out.

**Comment by alexander-somov** [comment]
А зачем переоткрыл?

**Comment by Dobroserdoff** [comment]
Осваиваюсь пока. Интерфейс-шминтервейс. Кнопки тыкаю.

**Comment by alexander-somov** [comment]
Хорошо. А я из почты ответить попробую.

пятница, 27 февраля 2015 г. пользователь Yury Dobroserdoff написал:
