### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by alexander-somov** [Dobroserdoff/parsek#5]
Я тут немного комментариев написал в новой ветке. Её можно не сливать, а только почитывать.

А ещё покопался и нашёл-таки способ посмотреть здесь, какие именно комиты были сделаны в ветке. См. картинку.
![screen](https://cloud.githubusercontent.com/assets/11215234/6410726/abdb9502-be82-11e4-9804-e48db3977f87.png)

**Comment by Dobroserdoff** [comment]
Прочитал-посмотрел. Что я могу сказать. Есть над чем поработать. Возьмусь за изменения после коммита адресов.

**Comment by alexander-somov** [comment]
Тьфу, блин. И я не на те кнопки жму.

**Comment by Dobroserdoff** [comment]
kekekeke

**Comment by alexander-somov** [comment]
В общем, я когда сделаю порцию комментариев, буду тебе issue открывать.

**Comment by Dobroserdoff** [comment]
Хорошо.

**Comment by Dobroserdoff** [comment]
Поиск по адресу сделал, выложил. Причёсываю код в связи с твоими пожеланиями. Возможно это займёт некоторое время.
